modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/BONNe/ChatReactionAbuse/issues" #optional
[[mods]] #mandatory
modId="reactionabusemod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Chat Reaction Abuse Mod" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/BONNe/ChatReactionAbuse/" #optional
#logoFile="examplemod.png" #optional
credits="" #optional
authors="BONNe1704" #optional
description='''
This mod allows to abuse Spigot plugin Chat Reaction.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.reactionabusemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[25,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="CLIENT"
# Here's another dependency
[[dependencies.reactionabusemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="CLIENT"